        !COMPILER-GENERATED INTERFACE MODULE: Tue Aug  1 13:12:18 2017
        MODULE BCOND_WQM__genmod
          INTERFACE 
            SUBROUTINE BCOND_WQM
            END SUBROUTINE BCOND_WQM
          END INTERFACE 
        END MODULE BCOND_WQM__genmod
