        !COMPILER-GENERATED INTERFACE MODULE: Tue Aug  1 13:12:13 2017
        MODULE ERROR_CHECK__genmod
          INTERFACE 
            SUBROUTINE ERROR_CHECK(HEADER,FLAG)
              CHARACTER(LEN=120) :: HEADER
              INTEGER(KIND=4) :: FLAG
            END SUBROUTINE ERROR_CHECK
          END INTERFACE 
        END MODULE ERROR_CHECK__genmod
