        !COMPILER-GENERATED INTERFACE MODULE: Tue Aug  1 13:12:13 2017
        MODULE GENMAP__genmod
          INTERFACE 
            SUBROUTINE GENMAP
            END SUBROUTINE GENMAP
          END INTERFACE 
        END MODULE GENMAP__genmod
