        !COMPILER-GENERATED INTERFACE MODULE: Tue Aug  1 12:58:34 2017
        MODULE INPUTS__genmod
          INTERFACE 
            SUBROUTINE INPUTS
            END SUBROUTINE INPUTS
          END INTERFACE 
        END MODULE INPUTS__genmod
