        !COMPILER-GENERATED INTERFACE MODULE: Tue Aug  1 13:12:13 2017
        MODULE INPUTS__genmod
          INTERFACE 
            SUBROUTINE INPUTS
            END SUBROUTINE INPUTS
          END INTERFACE 
        END MODULE INPUTS__genmod
