        !COMPILER-GENERATED INTERFACE MODULE: Tue Aug  1 12:58:31 2017
        MODULE NCD_READ_SHAPE__genmod
          INTERFACE 
            SUBROUTINE NCD_READ_SHAPE(INFILE)
              CHARACTER(LEN=1024), INTENT(IN) :: INFILE
            END SUBROUTINE NCD_READ_SHAPE
          END INTERFACE 
        END MODULE NCD_READ_SHAPE__genmod
