        !COMPILER-GENERATED INTERFACE MODULE: Tue Aug  1 10:57:54 2017
        MODULE NCD_READ_GRID__genmod
          INTERFACE 
            SUBROUTINE NCD_READ_GRID(INFILE)
              CHARACTER(LEN=1024), INTENT(IN) :: INFILE
            END SUBROUTINE NCD_READ_GRID
          END INTERFACE 
        END MODULE NCD_READ_GRID__genmod
