        !COMPILER-GENERATED INTERFACE MODULE: Tue Aug  1 12:58:33 2017
        MODULE PDOMDEC__genmod
          INTERFACE 
            SUBROUTINE PDOMDEC
            END SUBROUTINE PDOMDEC
          END INTERFACE 
        END MODULE PDOMDEC__genmod
