        !COMPILER-GENERATED INTERFACE MODULE: Tue Aug  1 12:58:25 2017
        MODULE PSTOP__genmod
          INTERFACE 
            SUBROUTINE PSTOP
            END SUBROUTINE PSTOP
          END INTERFACE 
        END MODULE PSTOP__genmod
