        !COMPILER-GENERATED INTERFACE MODULE: Tue Aug  1 13:12:04 2017
        MODULE PSTOP__genmod
          INTERFACE 
            SUBROUTINE PSTOP
            END SUBROUTINE PSTOP
          END INTERFACE 
        END MODULE PSTOP__genmod
