        !COMPILER-GENERATED INTERFACE MODULE: Tue Aug  1 10:57:48 2017
        MODULE PSTOP__genmod
          INTERFACE 
            SUBROUTINE PSTOP
            END SUBROUTINE PSTOP
          END INTERFACE 
        END MODULE PSTOP__genmod
