        !COMPILER-GENERATED INTERFACE MODULE: Tue Aug  1 13:12:18 2017
        MODULE VISCOF_H__genmod
          INTERFACE 
            SUBROUTINE VISCOF_H
            END SUBROUTINE VISCOF_H
          END INTERFACE 
        END MODULE VISCOF_H__genmod
